- id: doi:10.1111/ejn.70377
  category: featured
  image: https://onlinelibrary.wiley.com/cms/asset/5dde3af9-f215-401e-8858-b69c50a12f48/ejn70377-fig-0001-m.jpg

- id: doi:10.1007/s00359-025-01787-w
  category: featured
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00359-025-01787-w/MediaObjects/359_2025_1787_Fig2_HTML.png

- id: doi:10.1038/s41586-025-09135-3
  category: featured
  image: https://scx2.b-cdn.net/gfx/news/2025/stargazing-aussie-moth.jpg

- id: doi:10.1098/rspb.2023.0030
  category: featured
  image: https://trs.silverchair-cdn.com/trs/content_public/journal/rspb/issue/290/1997/5/m_rspb.2023.290.issue-1997.cover.gif?Expires=1794058638&Signature=uzWBKjgkNgjTv8JCxHGDXJYjYFEkuGgYpN6O0z-N8d4x13u48J4o5SkJrOZZjZ8pk-uNkeRQSimS-P5sbwc83i-V1ZWy6BCbThyN8ay1aS-6bEL3YT-q9qpC60~sGvZKmg3pR2wjR4BsyzVxCtIqlhEosMHn7ksQz6oIzBya4ej1ZOEWWigqwPp89NftOkgdmEPZv53dz3wDoocVmwRyMcxWtETw4uyyKeYnRqDo5xFRP4DoFhKe2L7mt-OWThJ20jm9VvLfCGGGXdI3q1kaRbJjOWyc3LNP8xGxHI9sNVC7Ajv6TWSq9C3ef0w2wvkvZoXGfdgmymPyziSqLyBLPQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
